const { readFileSync, writeFileSync } = require("node:fs");
const { resolve } = require("node:path");
const {
  STATIC_YEARS, possibleDates, mardiGrasDate, kingCakeDays, formatDate,
  formatWeekday, findDateIndex, classifyByIndex, yearAnswer, yearDescription,
} = require("../calculator.js");

const root = resolve(__dirname, "..");
const check = process.argv.includes("--check");
const origin = "https://ismardigrasearly.com";
const escape = (value) => String(value).replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;");
const links = ['<a href="/">This season</a>', ...STATIC_YEARS.map((year) => `<a href="/${year}">${year}</a>`)];
const template = readFileSync(resolve(root, "index.html"), "utf8").replace(
  /<!-- YEAR_LINKS -->[\s\S]*?<!-- \/YEAR_LINKS -->/,
  `<!-- YEAR_LINKS -->\n        ${links.join("\n        ")}\n        <!-- /YEAR_LINKS -->`
);

function output(file, content) {
  if (check) {
    if (readFileSync(resolve(root, file), "utf8") !== content) {
      throw new Error(`${file} is stale; run node scripts/generate-years.cjs`);
    }
  } else {
    writeFileSync(resolve(root, file), content);
  }
}

output("index.html", template);
for (const year of STATIC_YEARS) {
  const date = mardiGrasDate(year);
  const index = findDateIndex(date);
  const verdict = classifyByIndex(index);
  const title = escape(yearAnswer(year));
  const description = escape(yearDescription(year));
  let html = template
    .replace("<!-- Yes, this was totally vibe coded. -->", "<!-- Generated by scripts/generate-years.cjs; edit index.html and calculator.js. -->")
    .replace(/<title>.*?<\/title>/, `<title>${title}</title>`)
    .replace(/(<meta\s+(?:name|property)="(?:description|og:description|twitter:description)"\s+content=")[^"]*("\s*\/?>)/g, `$1${description}$2`)
    .replace(/(<meta\s+(?:name|property)="(?:og:title|twitter:title)"\s+content=")[^"]*("\s*\/?>)/g, `$1${title}$2`)
    .replace(/(<link rel="canonical" href=")[^"]*"/, `$1${origin}/${year}"`)
    .replace(/(<meta property="og:url" content=")[^"]*"/, `$1${origin}/${year}"`)
    .replace(/(<input id="yearInput"[^>]*)(\/>)/, `$1value="${year}" $2`)
    .replace('id="timelineMarker"', `id="timelineMarker" style="left: ${(index / (possibleDates.length - 1)) * 100}%"`);

  const values = {
    yearAnswer: yearAnswer(year), mardiDate: formatDate(date),
    mardiWeekday: formatWeekday(date), timelineMarkerLabel: formatDate(date),
    kingCakeDays: kingCakeDays(date), kingCakeEnd: formatDate(date),
    halvesResult: verdict.halves, thirdsResult: verdict.thirds, fourthsResult: verdict.fourths,
  };
  for (const [id, value] of Object.entries(values)) {
    html = html.replace(new RegExp(`(id="${id}"[^>]*>)[^<]*`), `$1${escape(value)}`);
  }
  output(`${year}.html`, html);
}

output("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${["/", ...STATIC_YEARS.map((year) => `/${year}`)].map((path) => `  <url><loc>${origin}${path}</loc></url>`).join("\n")}\n</urlset>\n`);
console.log(`${check ? "Checked" : "Generated"} ${STATIC_YEARS.length} year pages and sitemap.xml.`);
